name: Deploy to Cloudinary

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Cloudinary CLI
      - name: Install Cloudinary CLI
        run: |
          npm install -g cloudinary-cli

      # Configure Cloudinary Environment Variables
      - name: Configure Cloudinary Environment
        run: |
          echo "CLOUDINARY_URL=cloudinary://$CLOUDINARY_API_KEY:$CLOUDINARY_API_SECRET@$CLOUDINARY_CLOUD_NAME" > $GITHUB_ENV
        env:
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}

      # Upload to Cloudinary
      - name: Upload to Cloudinary
        run: |
          set -e # Ensure the script fails on error
          cld upload_folder ${GITHUB_WORKSPACE}/src/ --recursive true
          echo "Upload to Cloudinary completed successfully."
