name: Deploy
on:
  # manual trigger
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: release
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Tests pass
        run: yarn test

      - name: Build list
        run: yarn build

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@18351461ae08dde235c0ccee0633ec905f0b9a52
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Pin to IPFS
        id: upload
        uses: anantaramdas/ipfs-pinata-deploy-action@a551f37c17ec3961df7c3ad52e1cd266dfd3d7e7
        with:
          pin-name: Uniswap Default Token List
          path: "build/uniswap-default.tokenlist.json"
          pinata-api-key: ${{ secrets.PINATA_API_KEY }}
          pinata-secret-api-key: ${{ secrets.PINATA_API_SECRET_KEY }}

      - name: Update DNS with new IPFS hash
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_GATEWAY_ID: ${{ secrets.CLOUDFLARE_GATEWAY_ID }}
        uses: Uniswap/cloudflare-update-web3-gateway@b3205288b1c6d0acb63fa3bd8fb686c72a9e3f3e
        with:
          cid: ${{ steps.upload.outputs.hash }}
